// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/log-entry.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/log-entry.ts
var log_entry_default = defineTool({
  name: "log_entry",
  title: "Log food, drink, or medication",
  description: "Add a food, drink, or medication entry to the signed-in person's journal. Use for statements like 'I had oatmeal for breakfast'.",
  inputSchema: {
    type: z.enum(["food", "drink", "med"]).describe("What kind of entry this is."),
    label: z.string().trim().describe("Short name of the item, e.g. 'oatmeal with berries'."),
    carbs_grams: z.number().int().optional().describe("Estimated carbohydrates in grams."),
    portion_size: z.enum(["small", "medium", "large"]).optional().describe("Portion size."),
    logged_at: z.string().optional().describe("ISO 8601 timestamp of when it was consumed. Defaults to now."),
    notes: z.string().optional().describe("Any extra detail worth keeping with the entry.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("food_logs").insert({
      user_id: ctx.getUserId(),
      type: input.type,
      label: input.label,
      carbs_grams: input.carbs_grams ?? null,
      portion_size: input.portion_size ?? null,
      logged_at: input.logged_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      notes: input.notes ?? null,
      source: "text"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${data.label} at ${data.logged_at}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/list-entries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_entries_default = defineTool2({
  name: "list_entries",
  title: "List journal entries",
  description: "Read recent food, drink, and medication entries from the signed-in person's journal, newest first.",
  inputSchema: {
    days: z2.number().int().optional().describe("How many days back to look. Defaults to 1 (today)."),
    type: z2.enum(["food", "drink", "med"]).optional().describe("Only return this kind of entry."),
    limit: z2.number().int().optional().describe("Maximum entries to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const lookback = Math.min(Math.max(days ?? 1, 1), 365);
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    const since = new Date(Date.now() - lookback * 864e5).toISOString();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("food_logs").select("id, type, label, carbs_grams, portion_size, source, logged_at, notes").gte("logged_at", since).order("logged_at", { ascending: false }).limit(max);
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const totalCarbs = rows.reduce((s, r) => s + (r.carbs_grams ?? 0), 0);
    const summary = rows.length ? rows.map((r) => `${r.logged_at} \u2014 ${r.label} (${r.type}${r.carbs_grams ? `, ~${r.carbs_grams}g carbs` : ""})`).join("\n") : "No entries in that window.";
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { entries: rows, count: rows.length, total_carbs_grams: totalCarbs }
    };
  }
});

// src/lib/mcp/tools/glucose-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.4.3";
var LOW = 70;
var HIGH = 180;
var glucose_summary_default = defineTool3({
  name: "glucose_summary",
  title: "Glucose summary",
  description: "Summarize the signed-in person's continuous glucose readings over a period: average, time in range, and the most recent reading.",
  inputSchema: {
    days: z3.number().int().optional().describe("How many days back to summarize. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const lookback = Math.min(Math.max(days ?? 7, 1), 90);
    const since = new Date(Date.now() - lookback * 864e5).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cgm_readings").select("ts, mg_dl, trend").gte("ts", since).order("ts", { ascending: false }).limit(2e4);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const readings = data ?? [];
    if (readings.length === 0) {
      return {
        content: [{ type: "text", text: `No glucose readings in the last ${lookback} day(s).` }],
        structuredContent: { readings_count: 0, days: lookback }
      };
    }
    const values = readings.map((r) => Number(r.mg_dl));
    const avg = Math.round(values.reduce((s, v) => s + v, 0) / values.length);
    const pct = (n) => Math.round(n / values.length * 100);
    const inRange = pct(values.filter((v) => v >= LOW && v <= HIGH).length);
    const above = pct(values.filter((v) => v > HIGH).length);
    const below = pct(values.filter((v) => v < LOW).length);
    const latest = readings[0];
    return {
      content: [
        {
          type: "text",
          text: `Last ${lookback} day(s): average ${avg} mg/dL across ${readings.length} readings. Time in range ${inRange}% (above ${above}%, below ${below}%). Most recent: ${Math.round(Number(latest.mg_dl))} mg/dL at ${latest.ts}.`
        }
      ],
      structuredContent: {
        days: lookback,
        readings_count: readings.length,
        average_mg_dl: avg,
        time_in_range_pct: inRange,
        time_above_range_pct: above,
        time_below_range_pct: below,
        latest: { mg_dl: Number(latest.mg_dl), ts: latest.ts, trend: latest.trend }
      }
    };
  }
});

// src/lib/mcp/tools/list-medications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_medications_default = defineTool4({
  name: "list_medications",
  title: "List medications",
  description: "List the signed-in person's medications, with recent doses taken. Read-only \u2014 this never changes a prescription.",
  inputSchema: {
    include_stopped: z4.boolean().optional().describe("Include medications no longer taken. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_stopped }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("medications").select("id, name, med_class, dose, unit, schedule_cron, started_at, stopped_at").order("started_at", { ascending: false }).limit(100);
    if (!include_stopped) query = query.is("stopped_at", null);
    const { data: meds, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const since = new Date(Date.now() - 7 * 864e5).toISOString();
    const { data: events } = await supabase.from("medication_events").select("medication_id, taken_at, dose").gte("taken_at", since).order("taken_at", { ascending: false }).limit(200);
    const rows = meds ?? [];
    const summary = rows.length ? rows.map((m) => {
      const last = (events ?? []).find((e) => e.medication_id === m.id);
      return `${m.name}${m.dose ? ` ${m.dose}${m.unit ?? ""}` : ""} (${m.med_class})` + (last ? ` \u2014 last taken ${last.taken_at}` : " \u2014 no doses logged this week");
    }).join("\n") : "No medications on file.";
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { medications: rows, recent_doses: events ?? [] }
    };
  }
});

// src/lib/mcp/tools/daily-insight.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^4.4.3";
var daily_insight_default = defineTool5({
  name: "daily_insight",
  title: "Daily insight",
  description: "Fetch the most recent personalized daily insight generated for the signed-in person, including its narrative and suggestions.",
  inputSchema: {
    date: z5.string().optional().describe("Specific day as YYYY-MM-DD. Defaults to the latest available.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("daily_insights").select("insight_date, narrative, recommendations, metrics, data_sufficiency").order("insight_date", { ascending: false }).limit(1);
    if (date) query = query.eq("insight_date", date);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No insight available for that day yet." }],
        structuredContent: { insight: null }
      };
    }
    const recs = Array.isArray(data.recommendations) ? data.recommendations : [];
    const text = [
      `Insight for ${data.insight_date}:`,
      data.narrative ?? "(no narrative)",
      recs.length ? `Suggestions:
${recs.map((r) => `- ${typeof r === "string" ? r : JSON.stringify(r)}`).join("\n")}` : ""
    ].filter(Boolean).join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { insight: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "piaynhopsyvryikngxyq";
var mcp_default = defineMcp({
  name: "gentle-glucose-companion",
  title: "Gentle Glucose Companion",
  version: "0.1.0",
  instructions: "Tools for Calm Glucose, a gentle glucose companion. Use `log_entry` to record food, drinks, or medications; `list_entries` to review the journal; `glucose_summary` for average glucose and time in range; `list_medications` for the current medication list; and `daily_insight` for the latest personalized summary. Everything is scoped to the signed-in person. Never give medical advice or clinical thresholds \u2014 suggest checking with their care team instead.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [log_entry_default, list_entries_default, glucose_summary_default, list_medications_default, daily_insight_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
